services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  flask-app:
    image: python:3.12-slim
    container_name: flask-app
    working_dir: /srv/app
    command:
      - bash
      - -lc
      - |
        pip install --no-cache-dir -r requirements.txt
        exec gunicorn --bind 0.0.0.0:8000 app.flask_app:app
    environment:
      DEMO_MODE: ${DEMO_MODE}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_SECRET_KEY_FALLBACKS: ${FLASK_SECRET_KEY_FALLBACKS}
      FLASK_SESSION_COOKIE_SECURE: "true"
      FLASK_SESSION_TYPE: filesystem
      TRUSTED_PROXY_IPS: ${TRUSTED_PROXY_IPS}
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/${KEYCLOAK_REALM}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_REDIRECT_URI: ${OIDC_REDIRECT_URI}
      POST_LOGOUT_REDIRECT_URI: ${POST_LOGOUT_REDIRECT_URI}
      KEYCLOAK_CLIENT_SECRET: ""
      KEYCLOAK_SERVICE_CLIENT_SECRET: ${KEYCLOAK_SERVICE_CLIENT_SECRET}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      ALICE_TEMP_PASSWORD: ${ALICE_TEMP_PASSWORD}
      BOB_TEMP_PASSWORD: ${BOB_TEMP_PASSWORD}
    volumes:
      - .:/srv/app
    depends_on:
      - keycloak
    expose:
      - "8000"

  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: reverse-proxy
    depends_on:
      - flask-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro

volumes:
  keycloak_data:
