FROM hashicorp/terraform:1.9-alpine

RUN apk add --no-cache \
    bash \
    curl \
    ca-certificates \
    && rm -rf /var/cache/apk/*

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

WORKDIR /workspace

ENTRYPOINT ["terraform"]
